parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $snapshotThreshold: '%env(int:SNAPSHOT_THRESHOLD)%'

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Domain/Model/'
            - '../src/App/Kernel.php'

    # --- Domain Repositories Bindings ---

    # Write Side
    App\Domain\Repository\UserWriteRepositoryInterface: '@App\Infrastructure\Repository\DoctrineUserWriteRepository'
    App\Domain\Repository\ProductWriteRepositoryInterface: '@App\Infrastructure\Repository\DoctrineProductWriteRepository'
    App\Domain\Repository\SupplierWriteRepositoryInterface: '@App\Infrastructure\Repository\DoctrineSupplierWriteRepository'
    App\Domain\Repository\MenuWriteRepositoryInterface: '@App\Infrastructure\Repository\DoctrineMenuWriteRepository'
    App\Domain\Repository\BookingWriteRepositoryInterface: '@App\Infrastructure\Repository\DoctrineBookingWriteRepository'

    # Read Side
    App\Domain\Repository\UserReadRepositoryInterface: '@App\Infrastructure\Repository\DbalUserReadRepository'
    App\Domain\Repository\BookingReadRepositoryInterface: '@App\Infrastructure\Repository\DbalBookingReadRepository'
    App\Domain\Repository\SupplierReadRepositoryInterface: '@App\Infrastructure\Repository\DbalSupplierReadRepository'
    App\Domain\Repository\ProductReadRepositoryInterface: '@App\Infrastructure\Repository\DbalProductReadRepository'
    App\Domain\Repository\MenuReadRepositoryInterface: '@App\Infrastructure\Repository\DbalMenuReadRepository'

    # --- Factories ---
    _instanceof:
        App\Domain\Service\ProductDetailFactoryInterface:
            tags: ['app.product_detail_factory']

    # --- Infrastructure Services ---

    App\Infrastructure\Persistence\Doctrine\ReadEntityManager:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    App\Infrastructure\Persistence\Doctrine\WriteEntityManager:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'

    App\Infrastructure\Persistence\Mongo\MongoClient:
        arguments:
            $uri: '%env(MONGODB_URL)%'
            $dbName: '%env(MONGODB_DB)%'

    # Event Sourcing Repositories
    App\Domain\Repository\UserEventStoreRepositoryInterface: '@App\Infrastructure\Repository\UserEventSourcingRepository'
    App\Domain\Repository\BookingEventStoreRepositoryInterface: '@App\Infrastructure\Repository\BookingEventSourcingRepository'
    App\Domain\Repository\ProductEventStoreRepositoryInterface: '@App\Infrastructure\Repository\ProductEventSourcingRepository'
    App\Application\Bus\AsyncCommandBusInterface: '@App\Infrastructure\Messenger\Bus\MessengerAsyncCommandBus'
    App\Application\Bus\SyncCommandBusInterface: '@App\Infrastructure\Messenger\Bus\MessengerSyncCommandBus'

    # --- Application Handlers ---
    App\Application\Handler\:
        resource: '../src/App/Application/Handler'
        tags: ['messenger.message_handler']

    App\Infrastructure\Messenger\Transport\RedisTransportFactory:
        tags: ['messenger.transport_factory']

    App\Infrastructure\Messenger\Transport\KafkaTransportFactory:
        tags: ['messenger.transport_factory']
