parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $snapshotThreshold: '%env(int:SNAPSHOT_THRESHOLD)%'

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Domain/Model/'
            - '../src/App/Kernel.php'

    # --- Domain Repositories Bindings ---

    # Write Side
    App\Domain\Repository\UserWriteRepositoryInterface: '@App\Infrastructure\Repository\User\DoctrineUserWriteRepository'
    App\Domain\Repository\ProductWriteRepositoryInterface: '@App\Infrastructure\Repository\Product\DoctrineProductWriteRepository'
    App\Domain\Repository\SupplierWriteRepositoryInterface: '@App\Infrastructure\Repository\Supplier\DoctrineSupplierWriteRepository'
    App\Domain\Repository\MenuWriteRepositoryInterface: '@App\Infrastructure\Repository\Menu\DoctrineMenuWriteRepository'
    App\Domain\Repository\BookingWriteRepositoryInterface: '@App\Infrastructure\Repository\Booking\DoctrineBookingWriteRepository'

    # Read Side
    App\Domain\Repository\UserReadRepositoryInterface: '@App\Infrastructure\Repository\User\DbalUserReadRepository'
    App\Domain\Repository\BookingReadRepositoryInterface: '@App\Infrastructure\Repository\Booking\DbalBookingReadRepository'
    App\Domain\Repository\SupplierReadRepositoryInterface: '@App\Infrastructure\Repository\Supplier\DbalSupplierReadRepository'
    App\Domain\Repository\ProductReadRepositoryInterface: '@App\Infrastructure\Repository\Product\DbalProductReadRepository'
    App\Domain\Repository\MenuReadRepositoryInterface: '@App\Infrastructure\Repository\Menu\DbalMenuReadRepository'

    # --- Factories ---
    _instanceof:
        App\Domain\Service\ProductDetailFactoryInterface:
            tags: ['app.product_detail_factory']
        App\Domain\Derivation\Rule\Interface\DerivationRuleInterface:
            tags: ['app.derivation_rule']

    # --- Infrastructure Services ---

    App\Infrastructure\Persistence\Doctrine\ReadEntityManager:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    App\Infrastructure\Persistence\Doctrine\WriteEntityManager:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'

    App\Infrastructure\Persistence\Mongo\MongoClient:
        arguments:
            $uri: '%env(MONGODB_URL)%'
            $dbName: '%env(MONGODB_DB)%'

    # Event Sourcing Repositories
    App\Domain\Repository\UserEventStoreRepositoryInterface: '@App\Infrastructure\Repository\User\UserEventSourcingRepository'
    App\Domain\Repository\BookingEventStoreRepositoryInterface: '@App\Infrastructure\Repository\Booking\BookingEventSourcingRepository'
    App\Domain\Repository\ProductEventStoreRepositoryInterface: '@App\Infrastructure\Repository\Product\ProductEventSourcingRepository'
    App\Application\Bus\AsyncCommandBusInterface: '@App\Infrastructure\Messenger\Bus\MessengerAsyncCommandBus'
    App\Application\Bus\SyncCommandBusInterface: '@App\Infrastructure\Messenger\Bus\MessengerSyncCommandBus'

    # --- N8n Logger ---
    App\Integrations\N8n\Application\Service\N8nNotifier:
        arguments:
            $n8nLogger: '@monolog.logger.n8n'

    App\Integrations\N8n\Application\Service\SupplierProcess\N8nQuoteSentNotifier:
        arguments:
            $n8nLogger: '@monolog.logger.n8n'

    App\Integrations\N8n\Application\Service\SupplierProcess\SupplierResponseProcessCallbackRegistrar:
        arguments:
            $n8nLogger: '@monolog.logger.n8n'

    App\Integrations\N8n\Application\Service\SupplierProcess\SupplierResponseProcessCallbackUrlRegistrar:
        arguments:
            $n8nLogger: '@monolog.logger.n8n'

    # --- Custom App Logger ---
    App\Application\Logger\AppLogger:
        arguments:
            $logger: '@monolog.logger.custom'

    # --- Application Handlers ---
    App\Application\Handler\:
        resource: '../src/App/Application/Handler'

    App\Infrastructure\Messenger\Transport\RedisTransportFactory:
        tags: ['messenger.transport_factory']

    App\Infrastructure\Messenger\Transport\KafkaTransportFactory:
        tags: ['messenger.transport_factory']
