services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Infrastructure\Messenger\Fixtures\:
        resource: '../tests/Infrastructure/Messenger/Fixtures/'

    App\Tests\Infrastructure\Messenger\Fixtures\TestMessageHandler:
        tags: ['messenger.message_handler']

    App\Tests\Infrastructure\Messenger\Fixtures\TestFailingMessageHandler:
        tags: ['messenger.message_handler']

    App\Test\:
        resource: '../src/Test/'
        tags: ['controller.service_arguments']
