[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[inet_http_server]
port=*:9001
# No username/password for local dev, but can be added:
# username=user
# password=123

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://localhost:9001

[program:messenger-consume]
command=php /app/bin/console messenger:consume async failed --limit=1000 --time-limit=3600
user=root
numprocs=1
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
